- name: Demo on using variable
  hosts: all
  vars:
    URL: play.google.com      # Global variable
  vars_files: demo-vars.yaml
  vars_prompt:
    - name: URL
      prompt: Enter the url
  tasks:
    - name: Printing the URL Task 
      ansible.builtin.debug:
        msg: The value of URL is {{URL}} 

    - name: Printing the URL from the Task 
      ansible.builtin.debug:
        msg: The value of URL is {{URL}} 
      vars:
        URL: task.google.com      #Task / Local Level Variable ; The scope of is it only this task 

    - name: Printing the URL
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: task.google.com  

    - name: Printing the value supplied from command line
      ansible.builtin.debug:
        msg: "{{CMD_URL}}"

    - name: Printing the value supplied from file
      ansible.builtin.debug:
        msg: "{{GAME_LIVES}}"
 

# $URL is bash is equivalent to {{URL}} in YAML 

# Variable Precendence : 
# CLI Variables  > Local Variables > Global Variables > File Variables > Prompt Variables 


# When to specifically use Quites ? 
# When you're printing only the variable then enclose them in the Double Quotes.