- name: Demo on using variable
  hosts: all
  vars:
    URL: play.google.com      # Global variable
  tasks:
    - name: Printing the URL Task 
      ansible.builtin.debug:
        msg: The value of URL is {{URL}} 
    - name: Printing the URL from the Task 
      ansible.builtin.debug:
        msg: The value of URL is {{URL}} 
      vars:
        URL: task.google.com      