# When to use shell module
- name: Demo on registering variables
  hosts: all    # Mention the name of the inventory group that you want this to be running against 
  tasks:
    - name: Demo using shell module
      ansible.builtin.shell: uptime
      register: OUT

    - name: Printing the shell output using OUT variable
      ansible.builtin.debug: uptime
      msg: "{{OUT}}"