- name: Checking service up or not
  hosts: all    # Mention the name of the inventory group that you want this to be running against 
  tasks:
  - name: Check nginx running or not
    ansible.builtin.shell: ps -ef | grep nginx | grep -v grep
    ignore_errors: yes
  

  - name: Starting nginx
    ansible.builtin.debug:  
      msg: starging nginx on servers 

  - name: Check user id
    ansible.builtin.shell: id
    register: OUT

  - name: Printing
    ansible.builtin.debug:  
      msg: "{{OUT}}"


# When a task fails, the playbook will be a failure and will stop all the subsequent plays 
