- name: Configuring the nodejs
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -
    
- name: Installing nodejs 
  ansible.builtin.package:
    name: nodejs
    state: present


- name: Creating roboshop user
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop user account

- name: Download and extract frontend
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/catalogue/archive/main.zip
    dest: /tmp
    remote_src: yes  

- name: performing catalogue cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/catalogue/
    state: absent

- name: Copying catalogue to roboshop home directory
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes   #ensure your source copy is on the remote machine

- name: Installing npm to generate modules
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Copying systemd service
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Restarting the service 
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: yes
    name: "{{COMPONENT}}"