- name: Installing Python and Dependencies 
  ansible.builtin.yum:
    name: 
      - python36
      - gcc
      - python3-devel 
    state: present

# create user role

- name: Calling create user role
  ansible.builtin.include_role:
    name: common 
    tasks_from: create-user

# call download and extract

- name: Calling download and extract
  ansible.builtin.include_role:
    name: common 
    tasks_from: download

