- name: Configure Erlang repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Configure RabbitMq repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Installing RabbitMq 
  ansible.builtin.package:
    name: rabbitmq-server 
    state: present

- name: Starting RabbitMq
  ansible.builtin.service:
    name: rabbitmq-server
    state: started         
    enabled: yes

- name: Craeting app user for rabbitmq
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present