- name: Configuring the repo 
  ansible.builtin.shell: sudo rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Copying filebeat repo 
  ansible.builtin.template:
    src: elastic.repo 
    dest: /etc/yum.repos.d/elastic.repo 

- name: Installing filebeat 
  ansible.builtin.yum:
    name: filebeat 
    state: present  
  
- name: Copying filebeat config  
  ansible.builtin.template:
    src: filebeat.yml 
    dest: /etc/filebeat/filebeat.yml 

- name: ReStarting filebeat 
  ansible.builtin.service:
    name: filebeat 
    state: restarted       
    daemon_reload: yes 
    enabled: true