# Tast 1 : Copy the logstash config file from the logstash srever and put it in the templates
# Task 2 : Copy that templat to the logstash server after doing changes
# Task 3 : Restart the logstash server and wait till logstash comes up.
# Task 4 : Tag the input as JSON buy our logstash


- name: Copying LogstashConfig 
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
  notify: Restart logstash   # whenever there is change in file, only during the time this handlers will be called

- name: Start Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    daemon_reload: yes         
    enabled: yes

- name: Wait for logstash port to come in listening stage
  ansible.builtin.wait_for:
    port: 5044
    delay: 40
    timeout: 75