- name: Copying mysql Repo  
  ansible.builtin.copy:
    src: mysql.repo 
    dest: /etc/yum.repos.d/mysql.repo 

- name: Installing mysql 
  ansible.builtin.package:
    name: mysql-community-server 
    state: present  

- name: Starting mysql
  ansible.builtin.service:
    name: mysqld
    state: started          
    enabled: yes

# - name: Check the default password
#   block:
#     - name: Get Mysql version with non-default credentials
#       community.mysql.mysq_info:
#         login_user: root
#         login_password: RoboShop@1
#         filter: version
- name: Check the default password 
  block: 
    - name: Get MySQL version with non-default credentials
      community.mysql.mysql_info:
        login_user: root 
        login_password: RoboShop@1
        filter: version


  rescue:
    - name: Loading the file from remote
      ansible.builtin.slurp:
        src: /var/log/mysqld.log
      register: mysql_log

    - name: Fetch the password
      ansible.builtin.set_fact:
          DEFAULT_PASSWORD: "{{ mysql_log['content'] | b64decode | regex_findall('.*temporary password.*') | join (' ') | split(' ') | last}}"

    - name: Change mysql password
      ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';" | mysql --connect-expired-password -uroot -p"{{DEFAULT_PASSWORD}}"
  
 # if anyo of the tasks failes in a block then only rescue will run

