- name: Copying mysql Repo  
  ansible.builtin.copy:
    src: mysql.repo 
    dest: /etc/yum.repos.d/mysql.repo 

- name: Installing mysql 
  ansible.builtin.package:
    name: mysql-community-server 
    state: present  

- name: Starting mysql
  ansible.builtin.service:
    name: mysqld
    state: started          
    enabled: yes

- name: Loading the file from remote
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: mysql_log

- name: Read the file
  ansible.builtin.debug:
    msg: "{{ mysql_log['content'] | b64decode | regex_findall('temporary password')}}"

# - name: Change mysql password
#   ansible.builtin.shell:


  
# - name: Declaring the facts
#   ansible.builtin.set_facts:
#     Default_password: "{{}}"


