- name: Creating roboshop user
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop user account
  register: APPUSERINFO

# - name: Printing iser for dedbuging
#   ansible.builtin.debug:
#     msg: "{{APPUSERINFO}}"
