- name: Performing Cleanup of Old VERSION
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/ 
    state: absent 
  ignore_errors: yes

- name: Create {{COMPONENT}} Home directory
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/ 
    state: directory
    mode: '0755'
  become_user: "{{APPUSER}}"


- name: Download and extarct from the Nexus
  ansible.builtin.unarchive:
    src: http://172.31.7.205:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{VERSION}}.zip
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    remote_src: yes
  become_user: "{{APPUSER}}"


 

# - name: Download and extract frontend
#   ansible.builtin.unarchive:
#     src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
#     dest: /tmp
#     remote_src: yes  

# - name: performing catalogue cleanup
#   ansible.builtin.file:
#     path: /home/{{APPUSER}}/{{COMPONENT}}/
#     state: absent
#   ignore_errors: yes

# - name: Copying files to roboshop home directory
#   ansible.builtin.copy:
#     src: /tmp/{{COMPONENT}}-main/
#     dest: /home/{{APPUSER}}/{{COMPONENT}}/
#     owner: "{{APPUSER}}"
#     group: "{{APPUSER}}"
#     remote_src: yes
#   ignore_errors: yes