- name: Installing maven 
  ansible.builtin.package:
    name: maven 
    state: present

- name: Calling create user role
  ansible.builtin.include_role:
    name: common 
    tasks_from: create-user

# call download and extract

# - name: Calling download and extract role from common
#   ansible.builtin.include_role:
#     name: common 
#     tasks_from: download

- name: Calling download and extract role from common
  ansible.builtin.include_role:
    name: common 
    tasks_from: download-from-nexus

- name: Generating artifacts
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/

# Call config service

- name: Calling config service
  ansible.builtin.include_role:
    name: common 
    tasks_from: config-svc